spring:
  #https://docs.spring.io/spring-boot/reference/data/sql.html
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

    jpa:
      hibernate:
        ddl-auto: create
      properties:
        #コンソール出力なので、コメント化
#        show_sql: true
        format_sql: true

logging:
  level:
    #logger出力で利用
    org.hibernate.SQL: debug
